//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace simeFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db4Entities : DbContext
    {
        public db4Entities()
            : base("name=db4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<clientes> clientes { get; set; }
        public DbSet<clientes_credito> clientes_credito { get; set; }
        public DbSet<clientes_filiacao> clientes_filiacao { get; set; }
        public DbSet<itens_orcamento> itens_orcamento { get; set; }
        public DbSet<orcamentos> orcamentos { get; set; }
        public DbSet<produtos> produtos { get; set; }
        public DbSet<clientes_contatos> clientes_contatos { get; set; }
        public DbSet<clientes_indica> clientes_indica { get; set; }
        public DbSet<cod_sai> cod_sai { get; set; }
        public DbSet<entradas> entradas { get; set; }
        public DbSet<saida> saida { get; set; }
    }
}
