//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace simeFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes_credito
    {
        public int cod { get; set; }
        public Nullable<int> cod_cliente { get; set; }
        public string Credito { get; set; }
    
        public virtual clientes clientes { get; set; }
    }
}
