//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace simeFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class cod_sai
    {
        public Nullable<System.DateTime> Data { get; set; }
        public string Dado1 { get; set; }
        public string dado2 { get; set; }
        public string DADO3 { get; set; }
        public string DADO4 { get; set; }
        public string Dado5 { get; set; }
        public Nullable<int> Cod_cliente { get; set; }
        public Nullable<double> Especie { get; set; }
        public Nullable<double> Cheque { get; set; }
        public Nullable<double> Vale { get; set; }
        public string Especie1 { get; set; }
        public string Cheque1 { get; set; }
        public string Vale1 { get; set; }
        public Nullable<double> Troco { get; set; }
        public Nullable<int> Taxa { get; set; }
        public int Cod_sai1 { get; set; }
        public Nullable<double> Aliq { get; set; }
        public Nullable<int> OP { get; set; }
        public Nullable<int> CX { get; set; }
        public Nullable<double> cartao { get; set; }
    
        public virtual clientes clientes { get; set; }
    }
}
