//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace simeFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class entradas
    {
        public Nullable<int> Cod { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<bool> S_n { get; set; }
        public Nullable<int> Cod_fornecedor { get; set; }
        public string Nota { get; set; }
        public Nullable<System.DateTime> DataNota { get; set; }
        public Nullable<int> Local { get; set; }
        public Nullable<int> Origem { get; set; }
        public Nullable<int> Op { get; set; }
        public int Id { get; set; }
    }
}
