//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace simeFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class itens_orcamento
    {
        public Nullable<int> COD_ORCAMENTO { get; set; }
        public Nullable<int> COD_ITEM { get; set; }
        public Nullable<double> VALOR_CUSTO { get; set; }
        public Nullable<double> VALOR_VENDA { get; set; }
        public Nullable<double> QUANTIDADE { get; set; }
        public Nullable<int> COD_GRUPO { get; set; }
        public Nullable<double> PESO { get; set; }
        public int COD { get; set; }
        public Nullable<bool> FATURADO { get; set; }
        public Nullable<int> LOJA { get; set; }
        public Nullable<int> FORNECER { get; set; }
        public string NOTA { get; set; }
    }
}
