//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace simeFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class orcamentos
    {
        public int COD_ORCAMENTO { get; set; }
        public Nullable<int> COD_CLIENTE { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public Nullable<double> VALOR { get; set; }
        public Nullable<int> OP { get; set; }
        public Nullable<bool> APROVADO { get; set; }
        public Nullable<bool> MONTADO { get; set; }
        public Nullable<int> OP_MONTAGEM { get; set; }
        public Nullable<int> FORMA { get; set; }
        public Nullable<int> N_PARCELAS { get; set; }
        public Nullable<double> V_PARCELAS { get; set; }
        public Nullable<double> TAXA { get; set; }
        public Nullable<System.DateTime> DATA_FECHA { get; set; }
        public Nullable<bool> PROPOSTA_CANCELADA { get; set; }
        public Nullable<System.DateTime> DATA_MONTA { get; set; }
        public Nullable<System.DateTime> DATA_CONCLUSAO { get; set; }
        public string OBS { get; set; }
    }
}
