//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace simeFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class produtos
    {
        public int Cod { get; set; }
        public string Descrição { get; set; }
        public string Compatibilidade { get; set; }
        public string Cod_de_fabricação { get; set; }
        public Nullable<decimal> Custo { get; set; }
        public Nullable<double> Icm_de_Compra { get; set; }
        public Nullable<double> Taxa_de_frete { get; set; }
        public Nullable<double> IPI { get; set; }
        public Nullable<int> Tipo_de_cotação { get; set; }
        public Nullable<int> TIPO { get; set; }
        public Nullable<decimal> Expr5 { get; set; }
        public Nullable<decimal> Expr7 { get; set; }
        public string imagem { get; set; }
        public Nullable<bool> art33 { get; set; }
        public Nullable<double> peso { get; set; }
        public string Codbarras { get; set; }
        public Nullable<bool> desc { get; set; }
        public Nullable<int> REGRA { get; set; }
        public Nullable<double> Taxa_de_lucro_Grand { get; set; }
        public Nullable<double> Taxa_de_lucro_peq { get; set; }
        public Nullable<double> Valor_de_venda_Grd { get; set; }
        public Nullable<int> Valor_de_Venda_Peq { get; set; }
        public Nullable<decimal> Expr9 { get; set; }
        public Nullable<decimal> Expr6 { get; set; }
        public Nullable<decimal> Expr10 { get; set; }
        public Nullable<decimal> Expr8 { get; set; }
        public Nullable<double> TX_ATA_MIN { get; set; }
        public Nullable<double> TX_ATA_MAX { get; set; }
        public Nullable<double> TX_COR_MIN { get; set; }
        public Nullable<double> TX_COR_MAX { get; set; }
        public Nullable<int> MINI { get; set; }
        public Nullable<int> Medida { get; set; }
        public Nullable<float> COD_antigo { get; set; }
        public Nullable<double> Tx_desconto { get; set; }
        public string Politica { get; set; }
        public Nullable<int> NCM { get; set; }
        public Nullable<int> Estoque { get; set; }
    }
}
