//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace simeFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class saida
    {
        public Nullable<int> Cod_do_CD { get; set; }
        public Nullable<double> Quantidade { get; set; }
        public Nullable<double> Desconto { get; set; }
        public Nullable<int> cod_sai { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<decimal> Custo { get; set; }
        public Nullable<int> Percentual { get; set; }
        public int Cont { get; set; }
        public string Und { get; set; }
        public Nullable<bool> NL { get; set; }
        public Nullable<int> Op { get; set; }
        public Nullable<int> Loja { get; set; }
        public Nullable<int> Fornecedor { get; set; }
        public string NF { get; set; }
    }
}
